<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SignOut</name>
   <tag></tag>
   <elementGuidId>6a6faace-0b0d-4dbf-af22-f4ecdc895c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='navbar']//a[@href='/sign_out']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='navbar']//a[@href='/sign_out']</value>
   </webElementProperties>
</WebElementEntity>
